const verbs = [
  // Sección 1 (1-15)
  "Arose", "Arisen", "Elevar",
  "Was, were", "Been", "Ser",
  "Beat", "Beaten", "Golpear",
  "Became", "Become", "Convertirse",
  "Began", "Begun", "Comenzar",
  "Bet", "Bet", "Apostar",
  "Bit", "Bitten", "Morder",
  "Bled", "Bled", "Sangrar",
  "Blew", "Blown", "Soplar",
  "Broke", "Broken", "Romper",
  "Brought", "Brought", "Traer",
  "Built", "Built", "Construir",
  "Bought", "Bought", "Comprar",
  "Caught", "Caught", "Atrapar",
  "Chose", "Chosen", "Elegir",

  // Sección 2 (16-30)
  "Came", "Come", "Venir",
  "Cost", "Cost", "Costar",
  "Crept", "Crept", "Arrastrarse",
  "Cut", "Cut", "Cortar",
  "Dealt", "Dealt", "Negociar",
  "Did", "Done", "Hacer",
  "Drew", "Drawn", "Dibujar",
  "Dreamt", "Dreamt", "Soñar",
  "Drank", "Drunk", "Beber",
  "Drove", "Driven", "Conducir",
  "Ate", "Eaten", "Comer",
  "Fell", "Fallen", "Caer",
  "Fed", "Fed", "Alimentar",
  "Felt", "Felt", "Sentir",
  "Fought", "Fought", "Pelear",

  // Sección 3 (31-45)
  "Found", "Found", "Encontrar",
  "Fled", "Fled", "Huir",
  "Flew", "Flown", "Volar",
  "Forgot", "Forgotten", "Olvidar",
  "Forgave", "Forgiven", "Perdonar",
  "Forsook", "Forsaken", "Abandonar",
  "Froze", "Frozen", "Congelar",
  "Got", "Got", "Tener, obtener",
  "Gave", "Given", "Dar",
  "Went", "Gone", "Ir",
  "Ground", "Ground", "Moler",
  "Grew", "Grown", "Crecer",
  "Hung", "Hung", "Colgar",
  "Had", "Had", "Tener",
  "Heard", "Heard", "Oír",

  // Sección 4 (46-60)
  "Hid", "Hidden", "Esconderse",
  "Hit", "Hit", "Golpear",
  "Held", "Held", "Tener, mantener",
  "Hurt", "Hurt", "Herir",
  "Kept", "Kept", "Guardar",
  "Knelt", "Knelt", "Arrodillarse",
  "Knew", "Known", "Saber",
  "Led", "Led", "Liderar",
  "Learnt", "Learnt", "Aprender",
  "Left", "Left", "Dejar",
  "Lent", "Lent", "Prestar",
  "Let", "Let", "Permitir",
  "Lay", "Lain", "Yacer",
  "Lost", "Lost", "Perder",
  "Made", "Made", "Hacer",

  // Sección 5 (61-75)
  "Meant", "Meant", "Querer decir",
  "Met", "Met", "Conocer",
  "Paid", "Paid", "Pagar",
  "Put", "Put", "Poner",
  "Quit", "Quit", "Abandonar",
  "Read", "Read", "Leer",
  "Rode", "Ridden", "Montar, ir",
  "Rang", "Rung", "Llamar por teléfono",
  "Rose", "Risen", "Elevar",
  "Ran", "Run", "Correr",
  "Said", "Said", "Decir",
  "Saw", "Seen", "Ver",
  "Sold", "Sold", "Vender",
  "Sent", "Sent", "Enviar",
  "Set", "Set", "Fijar",

  // Sección 6 (76-90)
  "Sewed", "Sewn", "Coser",
  "Shook", "Shaken", "Sacudir",
  "Shone", "Shone", "Brillar",
  "Shot", "Shot", "Disparar",
  "Showed", "Shown", "Mostrar",
  "Shrank", "Shrunk", "Encoger",
  "Shut", "Shut", "Cerrar",
  "Sang", "Sung", "Cantar",
  "Sank", "Sunk", "Hundir",
  "Sat", "Sat", "Sentarse",
  "Slept", "Slept", "Dormir",
  "Slid", "Slid", "Deslizar",
  "Sowed", "Sown", "Sembrar",
  "Spoke", "Spoken", "Hablar",
  "Spelt/spelled", "Spelt/spelled", "Deletrear",

  // Sección 7 (90-105)
  "Spent", "Spent", "Gastar",
  "Spilt", "Spilt", "Derramar",
  "Split", "Split", "Dividir",
  "Spoilt", "Spoilt", "Estropear",
  "Spread", "Spread", "Extenderse",
  "Stood", "Stood", "Estar de pie",
  "Stole", "Stolen", "Robar",
  "Stung", "Stung", "Picar",
  "Stank", "Stunk", "Apestar",
  "Struck", "Struck", "Golpear",
  "Swore", "Sworn", "Jurar",
  "Swept", "Swept", "Trapear",
  "Swam", "Swum", "Nadar",
  "Took", "Taken", "Tomar",
  "Taught", "Taught", "Enseñar",

  // Sección 8 (106-118)
  "Tore", "Torn", "Rasgar",
  "Told", "Told", "Decir",
  "Thought", "Thought", "Pensar",
  "Threw", "Thrown", "Lanzar",
  "Trode", "Trodden/trod", "Pisotear",
  "Understood", "Understood", "Entender",
  "Woke", "Woken", "Despertarse",
  "Wore", "Worn", "Llevar puesto",
  "Wove", "Woven", "Tejer",
  "Wept", "Wept", "Llorar",
  "Won", "Won", "Ganar",
  "Wrung", "Wrung", "Retorcer",
  "Wrote", "Written", "Escribir"
];